#!/bin/bash
#SBATCH --job-name=__JOB_NAME__
#SBATCH --output=slurm-__COMPILER__-%a-%A.out
#SBATCH --error=slurm-__COMPILER__-%a-%A.err
#SBATCH --time=__TIMELIMIT__
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=__CPUS__
#SBATCH --mem=__MEM__
#SBATCH --account=__ACCOUNT__
#SBATCH --partition=__PARTITION__
#SBATCH --array=__ARRAY_SPEC__

# =============================================================================
# Stdlib Compilation Time Benchmark — SLURM array task
# =============================================================================
# One sbatch submission per compiler. SLURM expands the --array directive into
# RUNS_PER_COMPILER independent tasks. Each task uses $SLURM_ARRAY_TASK_ID as
# its run number and writes a single per-task JSON file:
#
#     results/stdlib-<compiler>-<run>.json
#
# That file captures everything needed for the thesis's reproducibility footer:
#   - wall-clock build time (date +%s.%N)
#   - peak resident-set memory (GNU /usr/bin/time -v)
#   - user/system CPU time
#   - exit code and a status string in {SUCCESS, TIMEOUT, OOM, ERROR}
#   - sac2c version, commit, branch, describe
#   - Stdlib commit, branch
#   - GCC, CMake, kernel, OS, CPU model, total memory
#   - SLURM job/array/partition/caps and the compute node
#
# The task script is generated by scripts/generate_jobs.sh, which fills the
# __PLACEHOLDERS__ below.
# =============================================================================

set -u  # treat unset variables as errors

# -------- placeholders filled by generate_jobs.sh -------------------------
COMPILER="__COMPILER__"
SAC2C_PATH="__SAC2C_PATH__"
SAC2C_DIR="__SAC2C_DIR__"
SAC2C_SRC="__SAC2C_SRC__"
STDLIB_SRC="__STDLIB_SRC__"
BUILD_TARGETS="__BUILD_TARGETS__"
BUILD_SYSTEM="__BUILD_SYSTEM__"
SLURM_MEM_REQUESTED="__MEM__"
SLURM_TIMELIMIT_REQUESTED="__TIMELIMIT__"
TEMP_ROOT_PREFERRED="__TEMP_ROOT_PREFERRED__"
TEMP_ROOT_FALLBACK="__TEMP_ROOT_FALLBACK__"

# -------- per-task identifiers --------------------------------------------
RUN_NUM="${SLURM_ARRAY_TASK_ID}"
JOB_ID="${SLURM_ARRAY_JOB_ID:-${SLURM_JOB_ID}}"
TASK_ID="${SLURM_ARRAY_TASK_ID}"
NODE_NAME="$(hostname -s)"
SUBMIT_DIR="${SLURM_SUBMIT_DIR:-$(pwd)}"
RESULT_JSON="${SUBMIT_DIR}/results/stdlib-${COMPILER}-${RUN_NUM}.json"
mkdir -p "${SUBMIT_DIR}/results"

# -------- helper: emit one JSON record ------------------------------------
emit_json () {
  local status="$1"
  local exit_code="$2"
  local compile_time="$3"
  local peak_rss_kb="$4"
  local user_cpu_s="$5"
  local sys_cpu_s="$6"
  local error_msg="$7"

  python3 - <<PY > "${RESULT_JSON}"
import json, os, sys
def numornull(v):
    return None if v in (None, "", "null") else float(v)
record = {
  "compiler": "${COMPILER}",
  "run": ${RUN_NUM},
  "status": "${status}",
  "exit_code": ${exit_code},
  "compilation_time_seconds": numornull("""${compile_time}"""),
  "peak_rss_kb": numornull("""${peak_rss_kb}"""),
  "user_cpu_s": numornull("""${user_cpu_s}"""),
  "sys_cpu_s": numornull("""${sys_cpu_s}"""),
  "started_at": os.environ.get("RUN_STARTED_AT", ""),
  "finished_at": os.environ.get("RUN_FINISHED_AT", ""),
  "job_id": "${JOB_ID}",
  "array_task_id": ${TASK_ID},
  "node": "${NODE_NAME}",
  "slurm_partition": os.environ.get("SLURM_JOB_PARTITION", ""),
  "slurm_cpus_per_task": int(os.environ.get("SLURM_CPUS_PER_TASK", "0") or 0),
  "slurm_mem_requested": "${SLURM_MEM_REQUESTED}",
  "slurm_timelimit_requested": "${SLURM_TIMELIMIT_REQUESTED}",
  "temp_build_root": os.environ.get("TEMP_BUILD_ROOT", ""),
  "sac2c_path": "${SAC2C_PATH}",
  "sac2c_version_raw": os.environ.get("SAC2C_VERSION_RAW", ""),
  "sac2c_commit": os.environ.get("SAC2C_COMMIT", ""),
  "sac2c_branch": os.environ.get("SAC2C_BRANCH", ""),
  "sac2c_describe": os.environ.get("SAC2C_DESCRIBE", ""),
  "stdlib_src": "${STDLIB_SRC}",
  "stdlib_commit": os.environ.get("STDLIB_COMMIT", ""),
  "stdlib_branch": os.environ.get("STDLIB_BRANCH", ""),
  "gcc_version": os.environ.get("GCC_VERSION", ""),
  "cmake_version": os.environ.get("CMAKE_VERSION", ""),
  "kernel": os.environ.get("KERNEL", ""),
  "os_release": os.environ.get("OS_RELEASE", ""),
  "cpu_model": os.environ.get("CPU_MODEL", ""),
  "total_memory_kb": int(os.environ.get("TOTAL_MEMORY_KB", "0") or 0),
  "build_targets": "${BUILD_TARGETS}",
  "build_system": "${BUILD_SYSTEM}",
  "error_message": """${error_msg}""",
}
json.dump(record, sys.stdout, indent=2, sort_keys=True)
sys.stdout.write("\n")
PY
}

# Always emit a JSON record on exit, even if we crashed early.
LAST_EXIT_CODE=0
on_exit () {
  LAST_EXIT_CODE=$?
  if [[ ! -f "${RESULT_JSON}" ]]; then
    emit_json "ERROR" "${LAST_EXIT_CODE}" "" "" "" "" "exited before result was recorded"
  fi
}
trap on_exit EXIT

echo "========================================================================"
echo "Stdlib Compilation Benchmark — task ${COMPILER}/${RUN_NUM}"
echo "========================================================================"
echo "Compiler : ${COMPILER}"
echo "Run      : ${RUN_NUM}"
echo "Job ID   : ${JOB_ID} (task ${TASK_ID})"
echo "Node     : ${NODE_NAME}"
echo "sac2c    : ${SAC2C_PATH}"
echo "Stdlib   : ${STDLIB_SRC}"
echo "Targets  : ${BUILD_TARGETS}"
echo "Build    : ${BUILD_SYSTEM}"
echo "CPUs     : ${SLURM_CPUS_PER_TASK:-?}"
echo "Mem cap  : ${SLURM_MEM_REQUESTED}"
echo "Time cap : ${SLURM_TIMELIMIT_REQUESTED}"
echo "========================================================================"

# -------- 1. Sanity checks -------------------------------------------------
if [[ ! -x "${SAC2C_PATH}" ]]; then
  emit_json "ERROR" 2 "" "" "" "" "sac2c binary not found or not executable: ${SAC2C_PATH}"
  exit 2
fi
if [[ ! -d "${STDLIB_SRC}" ]]; then
  emit_json "ERROR" 3 "" "" "" "" "stdlib source not found: ${STDLIB_SRC}"
  exit 3
fi

# -------- 2. Environment metadata -----------------------------------------
echo "Collecting environment metadata..."

export SAC2C_VERSION_RAW="$("${SAC2C_PATH}" -V 2>&1 | head -5 | tr '\n' '|' || true)"

if [[ -n "${SAC2C_SRC}" && -d "${SAC2C_SRC}/.git" ]]; then
  export SAC2C_COMMIT="$(git -C "${SAC2C_SRC}" rev-parse HEAD 2>/dev/null || echo "")"
  export SAC2C_BRANCH="$(git -C "${SAC2C_SRC}" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")"
  export SAC2C_DESCRIBE="$(git -C "${SAC2C_SRC}" describe --always --dirty --tags 2>/dev/null || echo "")"
else
  export SAC2C_COMMIT=""; export SAC2C_BRANCH=""; export SAC2C_DESCRIBE=""
fi

if [[ -d "${STDLIB_SRC}/.git" ]]; then
  export STDLIB_COMMIT="$(git -C "${STDLIB_SRC}" rev-parse HEAD 2>/dev/null || echo "")"
  export STDLIB_BRANCH="$(git -C "${STDLIB_SRC}" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")"
else
  export STDLIB_COMMIT=""; export STDLIB_BRANCH=""
fi

export GCC_VERSION="$(gcc --version 2>/dev/null | head -1 || echo "")"
export CMAKE_VERSION="$(cmake --version 2>/dev/null | head -1 || echo "")"
export KERNEL="$(uname -r 2>/dev/null || echo "")"
export OS_RELEASE="$( ( . /etc/os-release 2>/dev/null && echo "${PRETTY_NAME}" ) || echo "")"
export CPU_MODEL="$(lscpu 2>/dev/null | awk -F: '/^Model name/ {gsub(/^ +/,"",$2); print $2; exit}')"
export TOTAL_MEMORY_KB="$(awk '/^MemTotal:/ {print $2}' /proc/meminfo 2>/dev/null || echo 0)"

# -------- 3. Isolated SAC2C environment -----------------------------------
unset SAC2CRC SAC2C_STANDARD_PACKAGES SAC2C_INCLUDE_PATH SAC2C_LIBRARY_PATH
rm -rf "${HOME}/.sac2crc" "${HOME}/.sac2crc"* "${HOME}/.sac2c"*

export SAC2CBASE="${SAC2C_DIR}"
PRELUDE_PATH="${SAC2C_DIR}/runtime_build/src/runtime_libraries-build/lib/prelude"
export LD_LIBRARY_PATH="${SAC2C_DIR}/runtime_build/src/runtime_libraries-build/lib:${PRELUDE_PATH}:${LD_LIBRARY_PATH:-}"

mkdir -p "${HOME}/.sac2crc"
cat > "${HOME}/.sac2crc/sac2crc.release.prelude" <<EOF
/* Auto-generated for ${COMPILER} compiler */
target add_local:
TREEPATH       += "${PRELUDE_PATH}:"
LIBPATH        += "${PRELUDE_PATH}:"

target default_sbi :: add_local:
EOF
cp "${HOME}/.sac2crc/sac2crc.release.prelude" "${HOME}/.sac2crc/sac2crc.debug.prelude"

# -------- 4. Pick a fast temp build directory -----------------------------
# Radboud cluster docs: local /scratch is much, much faster than $HOME.
# Use /scratch/<user> if it exists and is writable, otherwise fall back.
choose_temp_root () {
  local pref="${TEMP_ROOT_PREFERRED:-/scratch}/${USER:-$LOGNAME}"
  if mkdir -p "${pref}" 2>/dev/null && [[ -w "${pref}" ]]; then
    echo "${pref}"; return
  fi
  echo "${TEMP_ROOT_FALLBACK:-$HOME}"
}
TEMP_ROOT="$(choose_temp_root)"
TEMP_BUILD_DIR="${TEMP_ROOT}/tmp_stdlib_build_${COMPILER}_${RUN_NUM}_${JOB_ID}_${TASK_ID}"
export TEMP_BUILD_ROOT="${TEMP_ROOT}"
export TMPDIR="${TEMP_BUILD_DIR}/tmp"
mkdir -p "${TMPDIR}" "${TEMP_BUILD_DIR}/build"

echo "Using temp build root: ${TEMP_ROOT}"
cd "${TEMP_BUILD_DIR}/build" || {
  emit_json "ERROR" 4 "" "" "" "" "cannot cd to build dir"
  exit 4
}

# -------- 5. Timed + memory-profiled build --------------------------------
TIME_LOG="${TEMP_BUILD_DIR}/time.log"
BUILD_LOG="${TEMP_BUILD_DIR}/build.log"

echo "Starting timed clean build (cmake + ${BUILD_SYSTEM} -j ${SLURM_CPUS_PER_TASK})..."
export RUN_STARTED_AT="$(date -Iseconds)"
START_TIME="$(date +%s.%N)"

BUILD_CMD="cmake -DTARGETS='${BUILD_TARGETS}' -DSAC2C_EXEC='${SAC2C_PATH}'"
if [[ "${BUILD_SYSTEM}" == "ninja" ]]; then
  BUILD_CMD+=" -GNinja '${STDLIB_SRC}' && ninja"
else
  BUILD_CMD+=" '${STDLIB_SRC}' && make -j ${SLURM_CPUS_PER_TASK}"
fi

/usr/bin/time -v -o "${TIME_LOG}" bash -c "${BUILD_CMD}" > "${BUILD_LOG}" 2>&1
BUILD_EXIT=$?

END_TIME="$(date +%s.%N)"
export RUN_FINISHED_AT="$(date -Iseconds)"
COMPILE_TIME="$(awk "BEGIN{printf \"%.6f\", ${END_TIME} - ${START_TIME}}")"

echo "----- last 60 lines of build log -----"
tail -n 60 "${BUILD_LOG}" || true
echo "--------------------------------------"

# -------- 6. Parse /usr/bin/time -v output --------------------------------
if [[ -f "${TIME_LOG}" ]]; then
  PEAK_RSS_KB="$(awk -F: '/Maximum resident set size/ {gsub(/^ +/, "", $2); print $2; exit}' "${TIME_LOG}")"
  USER_CPU_S="$(awk -F: '/User time \(seconds\)/ {gsub(/^ +/, "", $2); print $2; exit}' "${TIME_LOG}")"
  SYS_CPU_S="$(awk -F: '/System time \(seconds\)/ {gsub(/^ +/, "", $2); print $2; exit}' "${TIME_LOG}")"
else
  PEAK_RSS_KB=""; USER_CPU_S=""; SYS_CPU_S=""
fi

# -------- 7. Classify outcome ---------------------------------------------
STATUS="SUCCESS"
ERR_MSG=""
if [[ ${BUILD_EXIT} -ne 0 ]]; then
  if grep -qiE "killed|cgroup.*out of memory|oom-killer" "${BUILD_LOG}" 2>/dev/null; then
    STATUS="OOM"
    ERR_MSG="build killed (OOM)"
  elif [[ ${BUILD_EXIT} -eq 137 || ${BUILD_EXIT} -eq 124 ]]; then
    STATUS="TIMEOUT"
    ERR_MSG="build killed (timeout, exit ${BUILD_EXIT})"
  else
    STATUS="ERROR"
    ERR_MSG="build exited with ${BUILD_EXIT}"
  fi
  COMPILE_TIME=""
fi

# -------- 8. Emit final record --------------------------------------------
emit_json "${STATUS}" "${BUILD_EXIT}" "${COMPILE_TIME}" "${PEAK_RSS_KB}" "${USER_CPU_S}" "${SYS_CPU_S}" "${ERR_MSG}"

echo ""
echo "========================================================================"
echo "Result: ${STATUS} (exit ${BUILD_EXIT})"
[[ -n "${COMPILE_TIME}" ]] && echo "Wall-clock build time : ${COMPILE_TIME} s"
[[ -n "${PEAK_RSS_KB}"  ]] && echo "Peak RSS              : ${PEAK_RSS_KB} kB"
echo "Record written to     : ${RESULT_JSON}"
echo "========================================================================"

cd /
rm -rf "${TEMP_BUILD_DIR}"
exit ${BUILD_EXIT}
