#!/bin/bash
#SBATCH --job-name=stdlib-orig-11
#SBATCH --output=slurm-orig-11-%j.out
#SBATCH --error=slurm-orig-11-%j.err
#SBATCH --time=02:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=14G
#SBATCH --account=csmpi
#SBATCH --partition=csmpi_fpga_long

# =============================================================================
# Stdlib Compilation Time Benchmark - SLURM Job
# =============================================================================

# Build configuration (filled by generate_jobs.sh)
COMPILER="orig"
RUN_NUM="11"
SAC2C_PATH="/home/rhensen/sacoriginal/sac2c/build_p/sac2c_p"
STDLIB_SRC="/home/rhensen/Stdlib"
BUILD_TARGETS="seq;mt_pth"
BUILD_SYSTEM="make"
SAC2C_DIR="/home/rhensen/sacoriginal/sac2c/build_p"

# Create unique temporary build directory
TEMP_BUILD_DIR="${HOME}/tmp_stdlib_build_${COMPILER}_${RUN_NUM}_${SLURM_JOB_ID}"

# Isolate library paths to prevent cross-contamination between compilers
# This ensures each compiler uses its own prelude and runtime libraries

# Clear any existing SAC2C environment variables that might cause conflicts
unset SAC2CRC
unset SAC2C_STANDARD_PACKAGES
unset SAC2C_INCLUDE_PATH
unset SAC2C_LIBRARY_PATH

# CRITICAL: Remove the ~/.sac2crc/ directory which contains cached library paths
# This directory points to prelude paths and will cause cross-compiler contamination
echo "Clearing cached SAC2C configuration..."
rm -rf "${HOME}/.sac2crc" "${HOME}/.sac2crc"* "${HOME}/.sac2c"*

# Set compiler base directory so it can find its packages
export SAC2CBASE="${SAC2C_DIR}"

# Set compiler-specific runtime library path
export LD_LIBRARY_PATH="${SAC2C_DIR}/runtime_build/src/runtime_libraries-build/lib:${SAC2C_DIR}/runtime_build/src/runtime_libraries-build/lib/prelude:${LD_LIBRARY_PATH}"

# Create ~/.sac2crc/ directory and prelude configuration files
# This tells sac2c where to find the prelude for this specific compiler
echo "Creating SAC2C configuration for ${COMPILER} compiler..."
mkdir -p "${HOME}/.sac2crc"

# Prelude path for this compiler
PRELUDE_PATH="${SAC2C_DIR}/runtime_build/src/runtime_libraries-build/lib/prelude"

# Create sac2crc.release.prelude with compiler-specific paths
cat > "${HOME}/.sac2crc/sac2crc.release.prelude" << EOF
/****************************************************************************
 * Prelude configuration for ${COMPILER} compiler
 * Auto-generated by stdlib benchmark job
 ****************************************************************************/
target add_local:
TREEPATH       += "${PRELUDE_PATH}:"
LIBPATH        += "${PRELUDE_PATH}:"

target default_sbi :: add_local:
EOF

# Create sac2crc.debug.prelude (same as release for benchmarking)
cp "${HOME}/.sac2crc/sac2crc.release.prelude" "${HOME}/.sac2crc/sac2crc.debug.prelude"

echo "SAC2C configuration created successfully"
echo "Prelude path: ${PRELUDE_PATH}"
echo "Configuration files:"
ls -la "${HOME}/.sac2crc/" 2>/dev/null

# Isolate temp directory
export TMPDIR="${TEMP_BUILD_DIR}/tmp"
mkdir -p "${TMPDIR}"

echo "========================================"
echo "Stdlib Compilation Benchmark"
echo "========================================"
echo "Compiler: $COMPILER"
echo "Run: $RUN_NUM"
echo "Job ID: $SLURM_JOB_ID"
echo "Node: $(hostname)"
echo "Temp Build Dir: $TEMP_BUILD_DIR"
echo "SAC2C: $SAC2C_PATH"
echo "Stdlib Source: $STDLIB_SRC"
echo "Build Targets: $BUILD_TARGETS"
echo "Build System: $BUILD_SYSTEM"
echo "CPUs: $SLURM_CPUS_PER_TASK"
echo "========================================"
echo ""

# Initialize result CSV for this job
SUBMIT_DIR="${SLURM_SUBMIT_DIR:-$(pwd)}"
RESULT_FILE="${SUBMIT_DIR}/results/stdlib-${COMPILER}-${RUN_NUM}.csv"
mkdir -p "${SUBMIT_DIR}/results"
echo "compiler,run,compilation_time_seconds,job_id,node,timestamp" > "$RESULT_FILE"

# Verify SAC2C is accessible
if [ ! -x "$SAC2C_PATH" ]; then
    echo "ERROR: SAC2C compiler not found or not executable: $SAC2C_PATH"
    echo "${COMPILER},${RUN_NUM},ERROR,-1,$(hostname),$(date -Iseconds)" >> "$RESULT_FILE"
    exit 1
fi

# Verify source directory exists
if [ ! -d "$STDLIB_SRC" ]; then
    echo "ERROR: Stdlib source directory not found: $STDLIB_SRC"
    echo "${COMPILER},${RUN_NUM},ERROR,-1,$(hostname),$(date -Iseconds)" >> "$RESULT_FILE"
    exit 1
fi

echo "Verifying compiler:"
"$SAC2C_PATH" -V 2>&1 | head -3
echo ""

echo "Environment isolation:"
echo "  SAC2CBASE: $SAC2CBASE"
echo "  Compiler dir: $SAC2C_DIR"
echo "  LD_LIBRARY_PATH (first 2 entries):"
echo "    ${LD_LIBRARY_PATH%%:*}"
echo "    $(echo "$LD_LIBRARY_PATH" | cut -d: -f2)"
echo "  Prelude library check:"
if [ -f "${SAC2C_DIR}/runtime_build/src/runtime_libraries-build/lib/prelude/tree/host/seq/libsacprelude_pTree.so" ]; then
    echo "    ${SAC2C_DIR}/runtime_build/.../prelude/.../libsacprelude_pTree.so: EXISTS"
else
    echo "    Prelude library: NOT FOUND (ERROR)"
fi
echo ""

echo "Creating temporary build directory..."
mkdir -p "$TEMP_BUILD_DIR" || {
    echo "ERROR: Failed to create temporary build directory"
    echo "${COMPILER},${RUN_NUM},ERROR,-1,$(hostname),$(date -Iseconds)" >> "$RESULT_FILE"
    exit 1
}

echo "Starting clean build..."
echo ""

# =============================================================================
# TIMED BUILD PROCESS
# =============================================================================

# Start high-precision timing
START_TIME=$(date +%s.%N)

# Change to temp directory
cd "$TEMP_BUILD_DIR" || {
    echo "ERROR: Failed to change to temp directory"
    echo "${COMPILER},${RUN_NUM},ERROR,-1,$(hostname),$(date -Iseconds)" >> "$RESULT_FILE"
    exit 1
}

# Create build directory
mkdir -p build || {
    echo "ERROR: Failed to create build directory"
    echo "${COMPILER},${RUN_NUM},ERROR,-1,$(hostname),$(date -Iseconds)" >> "$RESULT_FILE"
    exit 1
}

cd build || {
    echo "ERROR: Failed to change to build directory"
    echo "${COMPILER},${RUN_NUM},ERROR,-1,$(hostname),$(date -Iseconds)" >> "$RESULT_FILE"
    exit 1
}

# CMake configuration
echo "Running CMake configuration..."
if [ "$BUILD_SYSTEM" = "ninja" ]; then
    cmake -DTARGETS="$BUILD_TARGETS" \
          -DSAC2C_EXEC="$SAC2C_PATH" \
          -GNinja \
          "$STDLIB_SRC" || {
        echo "ERROR: CMake configuration failed"
        echo "${COMPILER},${RUN_NUM},ERROR,-1,$(hostname),$(date -Iseconds)" >> "$RESULT_FILE"
        cd /
        rm -rf "$TEMP_BUILD_DIR"
        exit 1
    }

    echo ""
    echo "Running Ninja build..."
    ninja || {
        echo "ERROR: Ninja build failed"
        echo "${COMPILER},${RUN_NUM},ERROR,-1,$(hostname),$(date -Iseconds)" >> "$RESULT_FILE"
        cd /
        rm -rf "$TEMP_BUILD_DIR"
        exit 1
    }
else
    cmake -DTARGETS="$BUILD_TARGETS" \
          -DSAC2C_EXEC="$SAC2C_PATH" \
          "$STDLIB_SRC" || {
        echo "ERROR: CMake configuration failed"
        echo "${COMPILER},${RUN_NUM},ERROR,-1,$(hostname),$(date -Iseconds)" >> "$RESULT_FILE"
        cd /
        rm -rf "$TEMP_BUILD_DIR"
        exit 1
    }

    echo ""
    echo "Running Make build..."
    make -j "$SLURM_CPUS_PER_TASK" || {
        echo "ERROR: Make build failed"
        echo "${COMPILER},${RUN_NUM},ERROR,-1,$(hostname),$(date -Iseconds)" >> "$RESULT_FILE"
        cd /
        rm -rf "$TEMP_BUILD_DIR"
        exit 1
    }
fi

# End timing
END_TIME=$(date +%s.%N)

# =============================================================================
# CALCULATE AND RECORD RESULTS
# =============================================================================

# Calculate compilation time
COMPILATION_TIME=$(echo "$END_TIME - $START_TIME" | bc)

echo ""
echo "========================================"
echo "Build completed successfully!"
echo "Compilation time: $COMPILATION_TIME seconds"
echo "========================================"

# Record result
echo "${COMPILER},${RUN_NUM},${COMPILATION_TIME},${SLURM_JOB_ID},$(hostname),$(date -Iseconds)" >> "$RESULT_FILE"

# =============================================================================
# CLEANUP
# =============================================================================

echo ""
echo "Cleaning up temporary build directory..."
cd /
rm -rf "$TEMP_BUILD_DIR"

echo "Job complete. Results saved to $RESULT_FILE"
